export const GET_ALL_TODO = "GET_ALL_TODO";
export const ADD_TODO = "ADD_TODO";
export const COMPLETE_TODO = "COMPLETE_TODO";
export const REMOVE_TODO = "REMOVE_TODO";
export const CLEAR_COMPLETED_TODOS = "CLEAR_COMPLETED_TODOS";
export const FILTER_TODO = "FILTER_TODO";
export const TOGGLE_THEME = "TOGGLE_THEME";